development:
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: cap1_development
  username: dbuser
  password: db123456
  host: localhost


test:
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: cap1_test
  username: dbuser
  password: db123456
  host: localhost


production:
  database: cap1_production
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost
  username: dbuser
  password: db123456
  # password: <%= ENV['CAP1_DATABASE_PASSWORD'] %>